name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup docker build
        uses: docker/setup-buildx-action@v1

      - name: Login to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fattfatt/telebot:latest

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and run docker via ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/telebot
            git pull origin master
            cat << EOF > .env 
            TBTOKEN=${{ secrets.TBTOKEN }}
            TBDBUSER=${{ secrets.TBDBUSER }}
            TBDBPWD=${{ secrets.TBDBPWD }}
            TBDB=${{ secrets.TBDB }}
            MONGO_HOST=${{ secrets.MONGO_HOST }}
            MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}
            MONGO_USER=${{ secrets.MONGO_USER }}
            MONGO_PWD=${{ secrets.MONGO_PWD }}
            REDDITCLIENTID=${{ secrets.REDDITCLIENTID }}
            REDDITCLIENTSECRET=${{ secrets.REDDITCLIENTSECRET }}
            REDDITREFRESHTOKEN=${{ secrets.REDDITREFRESHTOKEN }}
            REDDITACCESSTOKEN=${{ secrets.REDDITACCESSTOKEN }}
            BANNEDUSERID=${{ secrets.BANNEDUSERID }}
            VVIMG=${{ secrets.VVIMG }}
            FBIMG=${{ secrets.FBIMG }}
            BLANK=${{ secrets.BLANK }}
            ADMIN_ID=${{ secrets.ADMIN_ID }}
            STUDENT_SERVICE_URL=${{ secrets.STUDENT_SERVICE_URL }}
            BMUSUKO_API_URL=${{ secrets.BMUSUKO_API_URL }}
            GC_PROJECT_ID=${{ secrets.GC_PROJECT_ID }}
            GC_KEY=${{ secrets.GC_KEY }}
            GC_BUCKET=${{ secrets.GC_BUCKET }}
            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
            S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            EOF
            docker-compose pull
            docker-compose down
            docker-compose up -d
